### ISSUE TITLE
青龙跑在查询的时候提示下面问题，请教一下大佬怎么解决呀?

### ISSUE THREAD

**Issue by geminicc** [mrabit/xmtravel#15]
(node:30928) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by mrabit** [comment]
这应该是nodejs版本导致的警告  可以切换到其他版本nodejs试试  

警告并不会影响正常执行
