### ISSUE TITLE
大佬，第二个无法拉取

### ISSUE THREAD

**Issue by 745243** [mrabit/xmtravel#4]
提示Please make sure you have the correct access rights
and the repository exists.

**Comment by Kky0125** [comment]
我也是，这个需要梯子吗？
C:\Users\admin>git clone git@github.com:mrabit/xmtravel.git
Cloning into 'xmtravel'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mrabit** [comment]
> 我也是，这个需要梯子吗？ C:\Users\admin>git clone [git@github.com](mailto:git@github.com):mrabit/xmtravel.git Cloning into 'xmtravel'... [git@github.com](mailto:git@github.com): Permission denied (publickey). fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.

走不了 ssh 的话试试 https 去拉仓库
