### ISSUE TITLE
青龙添加环境变量无效

### ISSUE THREAD

**Issue by Mr-NB** [mrabit/xmtravel#8]
![image](https://user-images.githubusercontent.com/35053330/178406925-f06de964-dfaa-4993-b5ea-eae988b00685.png)
![image](https://user-images.githubusercontent.com/35053330/178406964-1a2b2b4a-f643-471c-8156-23375ebe9826.png)
麻烦大神看下

**Comment by mrabit** [comment]
环境变量里的value值是怎么设置的呢, 是否启用

**Comment by Mr-NB** [comment]
![image](https://user-images.githubusercontent.com/35053330/178411110-45728a7c-b8d5-42f6-b344-d196f28adfdc.png)
设置也启用了， 但是没有生效

![image](https://user-images.githubusercontent.com/35053330/178411234-61ba93b2-0faa-450d-952b-97f300ce8d38.png)
我把cookie 直接放到代码里面可以跑

**Comment by mrabit** [comment]
已修复 青龙面板的脚本更新后试试呢
