### ISSUE TITLE
需求,麻烦大佬

### ISSUE THREAD

**Issue by Mr-NB** [mrabit/xmtravel#9]
1. 是否可以支持多个账号
2. 是否可以 酿酒，探索 功能

**Comment by mrabit** [comment]
青龙面板的话, 可以设置多个 MT_COOKIE 的环境变量  或者设置一个环境变量通过 & 或者 换行 区分账号

本地启动的话, config.js 里的配置项支持设置数组

暂时不考虑酿酒和探索, 因为本身规则是每月只能获取到 30 点的小茅运, 当前脚本可以完全满足

**Comment by Cyiming** [comment]
> 青龙面板的话, 可以设置多个 MT_COOKIE 的环境变量 或者设置一个环境变量通过 & 或者 换行 区分账号
> 
> 本地启动的话, config.js 里的配置项支持设置数组
> 
> 暂时不考虑酿酒和探索, 因为本身规则是每月只能获取到 30 点的小茅运, 当前脚本可以完全满足

其实是有需求的 大佬知不知道去年300点兑换百分百中奖的活动？平时不攒，活动开始后就来不及了
